import { useState } from 'react';
import * as Menu from '@ariakit/react/menu';
import { BarChart3, RefreshCw } from 'lucide-react';
import { Button, OGDialog, OGDialogContent, OGDialogHeader, OGDialogTitle } from '@librechat/client';
import { useGetAittcoQuotaQuery, useGetAittcoUsageQuery } from '~/data-provider';
import { useLocalize } from '~/hooks';

export default function QuotaSummary({ compact = false }: { compact?: boolean }) {
  const localize = useLocalize(); const [open, setOpen] = useState(false); const [details, setDetails] = useState(false); const [refreshKey, setRefreshKey] = useState(0); const [page, setPage] = useState(1);
  const quota = useGetAittcoQuotaQuery({ enabled: open }); const usage = useGetAittcoUsageQuery(refreshKey, { enabled: details });
  const items = usage.data?.items ?? []; const pageCount = Math.max(1, Math.ceil(items.length / 15)); const pageItems = items.slice((page - 1) * 15, page * 15); const usd = (value: number | null | undefined) => value == null ? '-' : `$${value.toFixed(2)}`; const usageUsd = (value: number | null) => value == null ? '-' : `$${(value / 500000).toFixed(4)}`;
  return <>
    <Menu.MenuProvider open={open} setOpen={setOpen} placement={compact ? 'bottom-end' : 'right-start'}>
      <Menu.MenuButton className="flex size-9 items-center justify-center rounded-lg p-2" aria-label={localize('com_ui_aittco_quota')} title={localize('com_ui_aittco_quota')}><BarChart3 className="icon-md" /></Menu.MenuButton>
      <Menu.Menu portal className="account-settings-popover popover-ui z-[126] w-[280px] rounded-lg p-4"><div className="flex items-center justify-between text-sm font-medium"><span>{localize('com_ui_aittco_quota_title')}</span><Button size="sm" variant="outline" onClick={() => quota.refetch()} disabled={quota.isFetching} aria-label={localize('com_ui_refresh')}><RefreshCw className="size-4" /></Button></div>{quota.data && <dl className="mt-3 grid grid-cols-2 gap-2 text-xs"><dt>{localize('com_ui_aittco_quota_total')}</dt><dd>{usd(quota.data.total)}</dd><dt>{localize('com_ui_aittco_quota_used')}</dt><dd>{usd(quota.data.used)}</dd><dt>{localize('com_ui_aittco_quota_remaining')}</dt><dd>{usd(quota.data.remaining)}</dd><dt>{localize('com_ui_aittco_quota_percentage')}</dt><dd>{quota.data.percentage == null ? '-' : `${quota.data.percentage}%`}</dd></dl>}<Button className="mt-3 w-full" size="sm" onClick={() => { setPage(1); setDetails(true); }}>{localize('com_ui_aittco_usage_details')}</Button></Menu.Menu>
    </Menu.MenuProvider>
    <OGDialog open={details} onOpenChange={setDetails}><OGDialogContent className="max-w-4xl"><OGDialogHeader><OGDialogTitle>{localize('com_ui_aittco_usage_title')}</OGDialogTitle></OGDialogHeader><div className="overflow-x-auto"><table className="min-w-[620px] text-sm"><thead><tr><th>{localize('com_ui_aittco_usage_time')}</th><th>{localize('com_ui_aittco_usage_model')}</th><th>{localize('com_ui_aittco_usage_input_tokens')}</th><th>{localize('com_ui_aittco_usage_output_tokens')}</th><th>{localize('com_ui_aittco_usage_quota')}</th></tr></thead><tbody>{pageItems.map((item) => <tr key={`${item.id}-${item.createdAt}`}><td>{new Date(item.createdAt).toLocaleString()}</td><td>{item.model ?? '-'}</td><td>{item.promptTokens}</td><td>{item.completionTokens}</td><td>{usageUsd(item.quota)}</td></tr>)}</tbody></table></div>{usage.data?.limited && <p className="mt-3 text-xs">{localize('com_ui_aittco_usage_limited')}</p>} {!usage.isLoading && !items.length && <p className="mt-3 text-sm">{localize('com_ui_aittco_usage_empty')}</p>}<div className="mt-4 flex items-center justify-between"><Button size="sm" variant="outline" onClick={() => setPage((value) => Math.max(1, value - 1))} disabled={page <= 1}>{localize('com_ui_aittco_usage_previous')}</Button><span className="text-sm">{localize('com_ui_aittco_usage_page', { 0: String(page), 1: String(pageCount) })}</span><Button size="sm" variant="outline" onClick={() => setPage((value) => Math.min(pageCount, value + 1))} disabled={page >= pageCount}>{localize('com_ui_aittco_usage_next')}</Button></div><Button className="mt-4" onClick={() => setRefreshKey((key) => key + 1)} disabled={usage.isFetching}><RefreshCw className="mr-2 size-4" />{localize('com_ui_aittco_usage_refresh')}</Button></OGDialogContent></OGDialog>
  </>;
}

