import axios, { AxiosError } from 'axios';
import type { Request, Response } from 'express';
export const AITTCO_USAGE_KEY_NOT_CONFIGURED='AITTCO_USAGE_KEY_NOT_CONFIGURED'; export const AITTCO_USAGE_AUTH_FAILED='AITTCO_USAGE_AUTH_FAILED'; export const UPSTREAM_USAGE_UNAVAILABLE='UPSTREAM_USAGE_UNAVAILABLE';
type Item={id:string|number|null;createdAt:string;model:string|null;quota:number|null;promptTokens:number;completionTokens:number}; type Deps={getUserKey:(args:{userId:string;name:string})=>Promise<unknown>;get?:typeof axios.get;now?:()=>number}; type Entry={items:Item[];expiresAt:number}; const TTL=60000, DEFAULT='https://api.aittco.com';
const unwrap=(b:unknown):unknown[]=>{if(Array.isArray(b))return b;if(!b||typeof b!=='object')return [];const o=b as Record<string,unknown>;if(o.success===false)return [];for(const c of [o.data,o.items,o.logs]){if(Array.isArray(c))return c;if(c&&typeof c==='object'){const n=c as Record<string,unknown>;for(const v of [n.items,n.logs,n.data])if(Array.isArray(v))return v;}}return [];};
const parse=(b:unknown):Item[]=>unwrap(b).flatMap(raw=>{if(!raw||typeof raw!=='object')return [];const r=raw as Record<string,unknown>;if(Number(r.type)!==2)return [];const t=Number(r.created_at??r.createdAt);if(!Number.isFinite(t))return [];const n=(v:unknown)=>typeof v==='number'&&Number.isFinite(v)?v:0;return [{id:typeof r.id==='string'||typeof r.id==='number'?r.id:null,createdAt:new Date((t>1e12?t:t*1000)).toISOString(),model:typeof(r.model_name??r.model)==='string'?String(r.model_name??r.model):null,quota:typeof r.quota==='number'&&Number.isFinite(r.quota)?r.quota:null,promptTokens:n(r.prompt_tokens),completionTokens:n(r.completion_tokens)}];}).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));
export function createAittcoUsageController({getUserKey,get=axios.get,now=Date.now}:Deps): { handle: (req: Request, res: Response) => Promise<Response>; clearCache: (u?: string) => void }{const cache=new Map<string,Entry>();const clearCache=(u?:string)=>u?cache.delete(u):cache.clear();const handle=async(req:Request,res:Response)=>{const user=req.user as {id?:string;_id?:unknown}|undefined;const uid=user?.id??(user?._id!=null?String(user._id):undefined);if(!uid)return res.status(404).json({error:AITTCO_USAGE_KEY_NOT_CONFIGURED,message:'AITTCO usage API key is not configured'});let stored:unknown;try{stored=await getUserKey({userId:uid,name:'aittco_shared'})}catch{stored=null}const token=typeof stored==='string'?(stored.trim()?stored:null):(stored&&typeof stored==='object'&&typeof (stored as {value?:unknown}).value==='string'?(stored as {value:string}).value:null);if(!token || stored === 'user_provided' || (stored && typeof stored==='object' && (stored as {user_provided?:boolean}).user_provided))return res.status(404).json({error:AITTCO_USAGE_KEY_NOT_CONFIGURED,message:'AITTCO usage API key is not configured'});const t=now(),refresh=req.query?.refresh==='true'||req.query?.refresh==='1',hit=cache.get(uid);if(!refresh&&hit&&hit.expiresAt>t)return res.status(200).json({source:'newapi',items:hit.items,limited:true});const base=(process.env.AITTCO_API_URL||DEFAULT).replace(/\/$/,'');let response;try{response=await get(`${base}/api/log/token`,{headers:{Authorization:`Bearer ${token}`},timeout:10000})}catch(e){const s=e instanceof AxiosError?e.response?.status:(e as {response?:{status?:number}})?.response?.status;if(s===404||s===405){try{response=await get(`${base}/api/log/token/`,{headers:{Authorization:`Bearer ${token}`},timeout:10000})}catch(f){const fs=(f as {response?:{status?:number}})?.response?.status;if(fs===401||fs===403)return res.status(fs).json({error:AITTCO_USAGE_AUTH_FAILED,message:'AITTCO usage API key was rejected'});return res.status(502).json({error:UPSTREAM_USAGE_UNAVAILABLE,message:'AITTCO usage service is unavailable'})}}else if(s===401||s===403)return res.status(s).json({error:AITTCO_USAGE_AUTH_FAILED,message:'AITTCO usage API key was rejected'});else return res.status(502).json({error:UPSTREAM_USAGE_UNAVAILABLE,message:'AITTCO usage service is unavailable'})}const items=parse(response?.data);cache.set(uid,{items,expiresAt:t+TTL});return res.status(200).json({source:'newapi',items,limited:true})};return {handle,clearCache};}




